replicaCount: 2

image:
  repository: ghcr.io/snehasipani/internal-developer-platform
  tag: "latest"
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi